### ISSUE TITLE
Stop working Automatic 1111

### ISSUE THREAD

**Issue by Rubenacp** [light-and-ray/sd-webui-color-correction-extras#2]
Whit the last actualization of this extension Automatic 1111 cant start. I deleted the extension folder to be able use automatic 1111

automatic1111 version:
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0-RC-110-g0fb34b57
Commit hash: 0fb34b57b80b368f76a368c50569371c10382e12

issue:
calling F:\stable-diffusion-webui\extensions\sd-webui-color-correction-extras\scripts\color_correction_extras.py/ui: InvalidVersion
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts_postprocessing.py", line 103, in wrap_call
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\extensions\sd-webui-color-correction-extras\scripts\color_correction_extras.py", line 59, in ui
    extraProcessVisiable = extraImagesAvaliable()
  File "F:\stable-diffusion-webui\extensions\sd-webui-color-correction-extras\scripts\color_correction_extras.py", line 12, in extraImagesAvaliable
    if packaging.version.parse(launch.git_tag()) >= packaging.version.parse("1.7.0"):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\packaging\version.py", line 54, in parse
    return Version(version)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\packaging\version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'v1.7.0-RC-110-g0fb34b57'

Traceback (most recent call last):
  File "F:\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "F:\stable-diffusion-webui\launch.py", line 44, in main
    start()
  File "F:\stable-diffusion-webui\modules\launch_utils.py", line 464, in start
    webui.webui()
  File "F:\stable-diffusion-webui\webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "F:\stable-diffusion-webui\modules\ui.py", line 850, in create_ui
    ui_postprocessing.create_ui()
  File "F:\stable-diffusion-webui\modules\ui_postprocessing.py", line 24, in create_ui
    script_inputs = scripts.scripts_postproc.setup_ui()
  File "F:\stable-diffusion-webui\modules\scripts_postprocessing.py", line 163, in setup_ui
    self.create_script_ui(script, inputs)
  File "F:\stable-diffusion-webui\modules\scripts_postprocessing.py", line 134, in create_script_ui
    for control in script.controls.values():
AttributeError: 'NoneType' object has no attribute 'values'
Creating model from config: F:\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: xformers... done.
model loaded.
Model loaded in 6.6s (load weights from disk: 0.7s, create model: 0.7s, apply weights to model: 1.7s, apply fp8: 1.8s, calculate empty prompt: 1.5s).
Presione una tecla para continuar . . .

**Comment by light-and-ray** [comment]
Hm, you should do "git checkout master". But I will fix it now adding try-except section
packaging.version.InvalidVersion: Invalid version: 'v1.7.0-RC-110-g0fb34b57'

Thanks for reporting

**Comment by light-and-ray** [comment]
Fixed. Can you try it before switching to master branch?

**Comment by Rubenacp** [comment]
Sorry I don't know how to try it before. I just copied the modifications to "scripts/color_correction_extras.py" but does not worked. Then I updated the extension and now it working well, thank you!
